title: Graphology
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
color_scheme: 'light'
search_enabled: false
aux_links:
  GitHub Repository: https://github.com/graphology/graphology
aux_links_new_tab: true
